FROM tomcat:7-jre8-alpine

#RUN apk add --no-cache mc

# mount with -v instead
#ADD ./NRG.war /usr/local/tomcat/webapps/NRG.war

# mount it with -v instead
#ADD ./wattos.runtime.properties /wattos.runtime.properties

# run with -e "JAVA_OPTS=-Duser.home=/"
#ENV JAVA_OPTS="-Duser.home=/"

# run with --expose=[8080,8009]
#EXPOSE 8080
#EXPOSE 8009

# base image's entrypoint is "catalina.sh run"
#
#CMD ["sh"]
#
