services:
  wattos-mysql:
    image: mysql:5
    container_name: wattos-mysql
    restart: always
    ports:
      - "3306:3306"
    user: "17473:10144"
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    volumes:
      - /projects/BMRB/public/wattos/wattos/initdb:/docker-entrypoint-initdb.d/
      - /projects/BMRB/public/wattos/dbfs:/wattos/dbfs
      - /projects/BMRB/public/wattos/html:/wattos/html
    command: --secure-file-priv=/wattos/dbfs

  wattos-tomcat:
    image: tomcat:7-jre8-alpine
    container_name: wattos-tomcat
    restart: always
    ports:
      - "8009:8009"
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Duser.home=/"
    volumes:
      - /projects/BMRB/public/wattos/wattos/wattos.runtime.properties.uchc:/wattos.runtime.properties
      - /projects/BMRB/public/wattos/wattos/NRG.war:/usr/local/tomcat/webapps/NRG.war
      - /projects/BMRB/public/wattos/dbfs:/wattos/dbfs
      - /projects/BMRB/public/ftp/pub/pdb:/pdb
    depends_on:
      - wattos-mysql
